export const PAGE = {
  home: "p-home",
  http: "p-http",
  sqli: "p-sqli",
  sqliId: "p-sqli-id",
  sqliWhat: "p-sqli-what",
  sqliDisc: "p-sqli-disc",
  sqliDb: "p-sqli-db",
  sqliAttacks: "p-sqli-attacks",
  sqliUnion: "p-sqli-union",
  sqliError: "p-sqli-error",
  sqliBoolean: "p-sqli-boolean",
  sqliTime: "p-sqli-time",
  sqliOob: "p-sqli-oob",
  sqliStacked: "p-sqli-stacked",
  sqliSecond: "p-sqli-second",
  sqliBypass: "p-sqli-bypass",
  sqliTools: "p-sqli-tools",
  sqliMap: "p-sqli-sqlmap",
  sqliDefense: "p-sqli-defense",
  sqliCheat: "p-sqli-cheat",
  sqliCheck: "p-sqli-check",
  xss: "p-xss",
  js: "p-js",
  jsTypes: "p-js-types",
  authn: "p-auth",
} as const;
